### PR TITLE
Symbol Change

### LINKED ISSUE #173: [PE-D] Event description/list checkbox symbols not displayed correctly
Checkbox symbol not showing properly on MacOS.

After `done personal 1`:

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zhixiangteoh/ped#2

### LINKED ISSUE #187: [PE-D] Cosmetic issue for ticks and crosses
As shown in picture.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: f0fz/ped#3

### LINKED ISSUE #201: [PE-D] [very minor] random character is displayed when an event is listed
CS2113T-T12-4

hello! im using a mac, so this may be a mac problem but i see this next to the "[Z]" not sure what it is supposed to mean

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: samuelchristopher/ped#1

### LINKED ISSUE #213: [PE-D] Output differs from the User Guide documentation
I followed through with the set up for the application. However, I am unable to display the tick and cross symbol. This error is persistent throughout the testing. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: e0425705/ped#1

### PR DESCRIPTION
**Pull request by Colin386**
Changed symbols from cross to "X" for not done, and from tick to "O" for done
Fixes #213 Fixes #201 Fixes #187

### CODE REVIEW

**Comment by matthewgani** [comment]
Maybe you can close those issues regarding the tick and cross?

**Comment by marcursor** [comment]
Fixes #173

**Comment by Colin386** [comment]
Fixes #213, Fixes #201, Fixes #187

**Comment by Colin386** [comment]
Fixes #213

**Pull request merged**
